### ISSUE TITLE
Lottery always alternate between Mushroom and +1 Level

### ISSUE THREAD

**Issue by herebefrogs** [mracette/js13k-2022#1]
I don't know if it's intentional or not, but there doesn't seem to be enough randomness to the lottery to ever land on 20x Stars or Heart.

I've given the code a cursory look. Though I don't fully understand it, it seems the arrow starts from the last lottery position, the spin duration is constant, and taking the deceleration rate into account, ends up at start position + Math.PI, causing the draw to alternate between Mushroom and +1 Level.

PS: I love the game and keep going back to it. The zen, visuals and sound feedback are exceptional.

**Comment by mracette** [comment]
Hey @herebefrogs! Thanks so much for filing this issue. I believe that I've been able to fix it with https://github.com/mracette/bardo/commit/37e448f4dc13b4f131e9927dc3c3a349dc2eaf42. I was able to get all 4 lottery outcomes in my tests. And still under 13k 😄

Thanks for your kind words on the game. I'm so happy you've enjoyed it. If you haven't already, you may want to check out Vampire Survivors which the core gameplay loop is inspired by. Cheers!

**Comment by herebefrogs** [comment]
Was able to verify on your `gh-pages` version 👍
